# Generated by Django 4.0.3 on 2022-04-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_id',
        ),
        migrations.AddField(
            model_name='session',
            name='board',
            field=models.FileField(default='', upload_to=None),
            preserve_default=False,
        ),
    ]
