# Generated by Django 4.0.3 on 2022-04-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_session_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(default='2020-10-10 12:10'),
            preserve_default=False,
        ),
    ]
