# Generated by Django 4.0.3 on 2022-04-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_session_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(default='2010-10-20 10:10'),
            preserve_default=False,
        ),
    ]
